# Generated by Django 2.2.4 on 2019-12-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo_app', '0002_doggo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='is_good_boy',
            field=models.BooleanField(default=False),
        ),
    ]
