# Generated by Django 2.2.4 on 2019-12-11 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo_app', '0004_doggo_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='birthday',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
            preserve_default=False,
        ),
    ]
