# Generated by Django 2.2.4 on 2019-12-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo_app', '0005_doggo_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='doggo',
            name='tricks',
        ),
        migrations.AddField(
            model_name='doggo',
            name='tricks',
            field=models.ManyToManyField(related_name='dogs_with_trick', to='doggo_app.Trick'),
        ),
    ]
